#!/bin/sh
# init script for statgrabber

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
EXEC=/usr/bin/perl
DAEMON=/usr/local/sbin/statgrabber
PIDFILE=/var/run/statgrabber.pid
NAME=statgrabber

case "$1" in
start)
	echo -n "Starting $NAME: "
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--exec $EXEC -- $DAEMON
	if [ $? != 0 ]; then
		echo "already running!"
		exit 1
	else
		echo done
	fi
	;;
stop)
	echo -n "Stopping $NAME: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--exec $EXEC -- $DAEMON
	if [ $? != 0 ]; then
		echo "not running!"
	else
		rm -f $PIDFILE
		echo done
	fi
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
