#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/sbin/dovecot
NAME=statgrabber

case "$1" in
start)
	echo -n "Starting $NAME"
	start-stop-daemon --start --quiet --oknodo --exec $DAEMON
	echo
	;;
stop)
	echo -n "Stopping $NAME "
	start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	echo
	;;
restart)
	echo -n "Restarting $DESC: $NAME"
	start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	start-stop-daemon --start --quiet --oknodo --exec $DAEMON
	echo
	;;
*)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
